//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduling
    {
        public int code { get; set; }
        public string id_student { get; set; }
        public int code_class { get; set; }
        public System.TimeSpan hour_ { get; set; }
        public Nullable<System.TimeSpan> hour_reach { get; set; }
        public Nullable<System.TimeSpan> hour_enter { get; set; }
        public Nullable<System.TimeSpan> hour_exit { get; set; }
    
        public virtual studens studens { get; set; }
    }
}
