//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class studens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public studens()
        {
            this.scheduling = new HashSet<scheduling>();
        }
    
        public string id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string id_parent { get; set; }
        public int code_class { get; set; }
    
        public virtual classes classes { get; set; }
        public virtual parents parents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scheduling> scheduling { get; set; }
    }
}
