//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PARENTSEntities1 : DbContext
    {
        public PARENTSEntities1()
            : base("name=PARENTSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classes> classes { get; set; }
        public virtual DbSet<instation> instation { get; set; }
        public virtual DbSet<parents> parents { get; set; }
        public virtual DbSet<request> request { get; set; }
        public virtual DbSet<scheduling> scheduling { get; set; }
        public virtual DbSet<studens> studens { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<times> times { get; set; }
    }
}
